# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0004_auto_20160721_2252'),
        ('remision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor'),
        ),
    ]
