# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_auto_20160721_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='cargo',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='celular',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='apellido',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
