# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_auto_20160721_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='vencimiento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
